version: '3'
services:
    php:
        build: ./docker
        container_name: php
        working_dir: /application
        expose:
            - '9000'
        depends_on:
            - database
        volumes:
            - ./app:/application

    nginx:
        image: nginx:1.19.6
        container_name: nginx
        ports:
            - 8003:80
        volumes:
            - ./app:/application
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    database:
        image: mysql:8.0
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}

    database_test:
        image: mysql:8.0
        container_name: database_test
        environment:
            - MYSQL_ROOT_PASSWORD=${TEST_DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${TEST_DB_NAME}
            - MYSQL_USER=${TEST_DB_USER}
            - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
