framework:
    messenger:
        failure_transport: failed
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default:
                middleware:
                    - dispatch_after_current_bus
                    - validation

            messenger.bus.command:
                middleware:
                    - dispatch_after_current_bus
                    - validation
                    - doctrine_transaction

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

            # Route your messages to the transports
            ## FOR ASYNC
            #'App\Application\Command\CreatePost\CreatePostCommand': async
